In [1]:
# Bibliotecas
import  os
import  yfinance                as      yf
import  pandas                  as      pd
import  numpy                   as      np
import  plotly.express          as      px
from    datetime                import  datetime, timedelta

In [2]:
# Seleccionamos el par a usar

lst_name = ['SOXL', 'SOXS']
# lst_name = ['SPXL', 'SPXS']
# lst_name = ['GUSH', 'DRIP']
# lst_name = ['NUGT', 'DUST']
# lst_name = ['YINN', 'YANG']
# lst_name = ['TQQQ', 'SQQQ']
# lst_name = [ 'FAS', 'FAZ' ]
# lst_name = [ 'EDC', 'EDZ' ]
# lst_name = [ 'TNA', 'TZA' ]
# lst_name = [ 'XPP', 'FXP' ]

# lst_name = ['NVDL', 'NVD' ] # NVDA
# lst_name = ['TSLR', 'TSDD'] # TSLA

In [3]:
# Obtener la hora actual
cu_time = datetime.now()                                # Current time

# Sumar 6 horas para ajustar con YF
ad_time = cu_time + timedelta(hours=6)                  # Adj time

# Darle formato para usar en YF, será nuestro End Date
en_time = ad_time
# en_date = ad_time.strftime("%Y-%m-%d_%H-%M-%S")
# en_date = ad_time.strftime("%Y-%m-%d")

# Vamos a definir nuestro Start Date
st_time = ad_time - timedelta(days=365*2)
# st_date = st_time.strftime("%Y-%m-%d_%H-%M-%S")
# st_date = st_time.strftime("%Y-%m-%d")

print( st_time, en_time )

df_data = yf.download( lst_name, start = st_time, end = en_time, auto_adjust=True, interval = "1d" ) 
df_data

2023-03-12 17:34:23.088466 2025-03-11 17:34:23.088466

[*********************100%***********************]  2 of 2 completed

Price           Close                   High                    Low  \
Ticker           SOXL        SOXS       SOXL        SOXS       SOXL
Date
2023-03-13  13.808890  205.595505  14.321060  218.342790  12.951990
2023-03-14  14.990820  186.838791  15.306001  198.038195  14.321059
2023-03-15  14.468799  193.940842  14.626390  205.959708  13.542954
2023-03-16  16.172749  171.633102  16.271243  199.586077  14.084672
2023-03-17  15.887116  174.273575  16.645522  177.642511  15.591635
...               ...         ...        ...         ...        ...
2025-03-05  21.950001   23.280001  22.160000   25.510000  20.120001
2025-03-06  19.230000   26.120001  21.020000   26.430000  19.010000
2025-03-07  20.879999   23.900000  21.090000   26.860001  18.750000
2025-03-10  17.990000   27.170000  19.799999   28.250000  17.100000
2025-03-11  16.736099   29.129900  18.320000   29.459999  16.510000

Price                        Open                 Volume
Ticker            SOXS       SOXL        SOXS       SOXL      SOXS
Date
2023-03-13  197.856082  13.405063  211.604931  121199400   6191520
2023-03-14  183.651969  14.537747  194.851374  107012500   5011050
2023-03-15  192.757162  14.380155  195.670825  126199700   4961980
2023-03-16  170.267322  14.261960  196.945573  108646600   5654660
2023-03-17  166.625210  16.241696  170.904653   79179200   4487700
...                ...        ...         ...        ...       ...
2025-03-05   23.059999  21.250000   24.180000  117702400  55916400
2025-03-06   24.280001  19.709999   25.690001  164277600  56345800
2025-03-07   23.639999  19.500000   25.900000  139349200  51858900
2025-03-10   25.160000  19.340000   25.700001  167930100  51485700
2025-03-11   26.690001  18.049999   27.139999  104246232  38380444

[501 rows x 10 columns]

In [4]:
precios = df_data[ df_data.columns[[0,1]] ]
precios

Price           Close
Ticker           SOXL        SOXS
Date
2023-03-13  13.808890  205.595505
2023-03-14  14.990820  186.838791
2023-03-15  14.468799  193.940842
2023-03-16  16.172749  171.633102
2023-03-17  15.887116  174.273575
...               ...         ...
2025-03-05  21.950001   23.280001
2025-03-06  19.230000   26.120001
2025-03-07  20.879999   23.900000
2025-03-10  17.990000   27.170000
2025-03-11  16.736099   29.129900

[501 rows x 2 columns]

In [5]:
fig = px.line( np.log( precios[('Close',)] ) )
fig.add_trace( px.scatter( np.log( precios[('Close',)] ) ).data[0] )
fig.add_trace( px.scatter( np.log( precios[('Close',)] ) ).data[1] )
fig.show()

In [6]:
# Guardar el gráfico como un archivo HTML
dir_gra = os.getcwd() + '/daily_pair.html'              # Filename direction
fig.write_html( dir_gra )